//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_XLIV_MilosPeric
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPizzaOrder
    {
        public int ID { get; set; }
        public int Amount { get; set; }
        public int OrderID { get; set; }
        public int PizzaID { get; set; }
    
        public virtual tblOrder tblOrder { get; set; }
        public virtual tblPizzaMenu tblPizzaMenu { get; set; }
    }
}
