//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_XLIV_MilosPeric
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPizzaShop
    {
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string JMBG { get; set; }
        public string OrderStatus { get; set; }
        public string PizzaName { get; set; }
        public string PIzzaType { get; set; }
        public string Price { get; set; }
        public int ID { get; set; }
        public int Amount { get; set; }
        public int OrderID { get; set; }
        public int PizzaID { get; set; }
    }
}
